[package]
name = "d2_p2"
version = "0.1.0"
authors = ["Asher Kaufman <blueyleader@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
